replicaCount: 2

image:
  repository: priyabratakhandual/rto-student-registration
  pullPolicy: IfNotPresent
  tag: "5"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5008

secretName: rto-secret

ingress:
  enabled: true
  className: nginx
  annotations: {}

  hosts:
    - host: ""
      paths:
        - path: /rto
          pathType: Prefix

  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

livenessProbe:
  httpGet:
    path: /ping
    port: 5008
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ping
    port: 5008
  initialDelaySeconds: 10
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}