containers:
  - name: frontend

    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

    imagePullPolicy: {{ .Values.image.pullPolicy }}

    ports:
      - name: http
        containerPort: 3000
        protocol: TCP

    {{- with .Values.resources }}
    resources:
      {{- toYaml . | nindent 12 }}
    {{- end }}

    {{- with .Values.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 12 }}
    {{- end }}